# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  capscroll_config = debug
endif
ifeq ($(config),release)
  capscroll_config = release
endif

PROJECTS := capscroll

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

capscroll:
ifneq (,$(capscroll_config))
	@echo "==== Building capscroll ($(capscroll_config)) ===="
	@${MAKE} --no-print-directory -C . -f capscroll.make config=$(capscroll_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f capscroll.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   capscroll"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"