# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  capnav_config = debug
endif
ifeq ($(config),release)
  capnav_config = release
endif

PROJECTS := capnav

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

capnav:
ifneq (,$(capnav_config))
	@echo "==== Building capnav ($(capnav_config)) ===="
	@${MAKE} --no-print-directory -C . -f capnav.make config=$(capnav_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f capnav.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   capnav"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"